### ISSUE TITLE
Add active service subscription mode

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/sdutil#5]
In an ideal world every service might interact with discoverd, but in practice, when I want to setup Wordpress, it would require a fair amount of work to make it subscribe to mysql service changes.

I'd like to know what the general opinion is on a mode that would make sdutil subscribe to a service, make it available as an environment variable, and then optionally restart the program if said service changes.

I.e.

```
 $ sdutil --provide mysql-db:MYSQL_IP reexec gunicorn wsgi.py
```

This would be a simple way to add service discovery to any service.

**Comment by titanous** [comment]
Yeah, we should do this somewhere in Flynn. The question is whether sdutil is responsible for it.
- Is it possible to expose multiple instances of a service?
- What about services that expect a more complex URI? (`postgres://`, `http://`, etc)
- Do we need a `SIGTERM`, `SIGKILL` progression with a timeout?

@progrium what do you think?

**Comment by progrium** [comment]
This _almost_ seems like it should live in sdutil, except I think it starts
to get more complicated than the common case for sdutil. Where sdutil exec
is really for registering a service, I think consuming services should be
addressed by a tool that also (optionally) renders configuration files as
well as restarting a process, etc.

So I'd like to see this functionality outside of sdutil. This is on my list
already, but it's not a priority for Flynn since our core components don't
need it. It would also be used for making Nginx and other config oriented
balancers/routers/frontends work with Flynn.

On Tue, Feb 4, 2014 at 10:04 AM, Jonathan Rudenberg <
notifications@github.com> wrote:

> Yeah, we should do this somewhere in Flynn. The only question is whether
> sdutil is responsible for it.
> - Is it possible to expose multiple instances of a service?
> - What about services that expect a more complex URI? (postgres://,
>   http://, etc)
> - Do we need a SIGTERM, SIGKILL progression with a timeout?
> 
> @progrium https://github.com/progrium what do you think?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/sdutil/issues/5#issuecomment-34074743
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by miracle2k** [comment]
Config file generation is a fantastic feature. Even then I still view this as a relatively simple use case for small/legacy apps, so I can see sdutil combining registry/consumption. The name is generic enough :) 

I don't feel strongly either way though. I'd happily write this as a separate project.

As to Jonathan's points:
- My Wordpress being restarted may just be serving a rendered page, so I would do a progression.
- +0 on supporting env variables that list multiple services. Doesn't seem all that useful to me.
- -0 on supporting a --prefix option. If a prefixed flag is the only way to provide the value, you can always use a wrapper script (might just be /bin/sh). Alternative: The tool could also replace vars in the command string itself before running it.

**Comment by progrium** [comment]
Actually I'm fine with it under sdutil as another subcommand. Perhaps an
"expose" command that lets you list services to expose and then a command
to run and restart when services change. An optional flag to specify a
template source and destination to render as well.

It could be a good idea to expose them in the environment in a format
compatible with Docker links:
http://docs.docker.io/en/latest/use/working_with_links_names/

On Tue, Feb 4, 2014 at 1:04 PM, Michael Elsdörfer
notifications@github.comwrote:

> Config file generation is a fantastic feature. Even then I still view this
> as a relatively simple use case for small/legacy apps, so I can see sdutil
> combining registry/consumption. The name is generic enough :)
> 
> I don't feel strongly either way though. I'd happily write this as a
> separate project.
> 
> As to Jonathan's points:
> - My Wordpress being restarted may just be serving a rendered page, so
>   I would do a progression.
> - +0 on supporting env variables that list multiple services. Doesn't
>   seem all that useful to me.
> - -0 on supporting a --prefix option. If a prefixed flag is the only
>   way to provide the value, you can always use a wrapper script (might just
>   be /bin/sh). Alternative: The tool could also replace vars in the command
>   string itself before running it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/sdutil/issues/5#issuecomment-34094554
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
@miracle2k Are you interested in implementing some of this functionality?

**Comment by miracle2k** [comment]
Yes, I was planning to work on it.

**Comment by miracle2k** [comment]
It will be common that a service needs both registry and consumption, i.e. both exec and expose commands. Should we just let the user call sdutil twice?

```
/bin/sdutil expose -s app-mysql /bin/sdutil exec wordpress:8080 nginx -p 8080
```

**Comment by titanous** [comment]
Yeah, I think calling it twice makes sense.
